name: animated_typing
description: A package to Animate the writing of the text.
version: 0.2.0
homepage: https://github.com/ammaratef45/animated_typing

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: